### ISSUE TITLE
Final class diagram

### ISSUE THREAD

**Issue by isaacsobczak** [isaacsobczak/BR16GroupAssignment1#16]

**Comment by isaacsobczak** [comment]
@idgormley, did you want to take a look at the project, and take another swing at the class diagram. I'll have a little time over lunch tomorrow if you can't get to it.

**Comment by idgormley** [comment]
Sure, I'll take a look at it once I get done with work at noon

**Comment by isaacsobczak** [comment]
Thanks!

**Comment by idgormley** [comment]
Alright I've updated it. It uses the same url as before. Let me know if I
have the associations put together right.

**Comment by isaacsobczak** [comment]
@idgormley, thanks. Scan through the PatientReadingsParser and the MainGui. The Trial class is never instantiated, and neither is the Reading class. I bet we could leave them off the final diagram. Patients are created, but only for their id. The collection of Readings within each patient was never used. It is cool that the URL stays the same.

**Comment by idgormley** [comment]
ok, I've made a new revision.

**Comment by isaacsobczak** [comment]
As long as the link is the same, I'm going to cut the release.

**Comment by idgormley** [comment]
Sure, I'll take a look at it once I get done with work at noon


On Feb 6, 2018 11:04 PM, "Isaac Sobczak" <notifications@github.com> wrote:

@idgormley <https://github.com/idgormley>, did you want to take a look at
the project, and take another swing at the class diagram. I'll have a
little time over lunch tomorrow if you can't get to it.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/isaacsobczak/BR16GroupAssignment1/issues/16#issuecomment-363658288>,
or mute the thread
